default:
  PLUGIN_ID:      com.plexapp.plugins.mlb
  PLUGIN_NAME:    Major League Baseball
  PLUGIN_VERSION: 0.2-beta
  PLUGIN_AUTHOR:  Rick Fletcher <fletch@pobox.com>

  # turn on debug options in the plugin plist?
  PLUGIN_DEBUG_MODE: 0

# override some values when building a dev release
development:
  PLUGIN_DEBUG_MODE: 1